#!/usr/bin/env python3
"""Small HTTP gateway around SOEM sample executables.

The gateway intentionally supervises external SOEM binaries instead of linking
SOEM into Python. That keeps the boundary explicit: SOEM owns EtherCAT/BPF
access, while this script exposes a simple process-control and status API that
can be driven by Testknecht or other automation tools.
"""

from __future__ import annotations

import argparse
import json
import os
import signal
import subprocess
import sys
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlparse
from uuid import uuid4


DEFAULT_LOG_LINES = 300


@dataclass
class GatewayConfig:
    interface: str | None
    host: str
    port: int
    simple_ng: Path
    slaveinfo: Path
    log_lines: int
    start_with_sudo: bool
    inventory_with_sudo: bool


@dataclass
class MasterState:
    interface: str | None = None
    process: subprocess.Popen[str] | None = None
    started_at: float | None = None
    stopped_at: float | None = None
    last_returncode: int | None = None
    last_error: str | None = None
    log: deque[str] = field(default_factory=lambda: deque(maxlen=DEFAULT_LOG_LINES))
    lock: threading.RLock = field(default_factory=threading.RLock)

    def append_log(self, line: str) -> None:
        with self.lock:
            self.log.append(line.rstrip("\n"))

    def status(self) -> dict[str, Any]:
        with self.lock:
            running = self.process is not None and self.process.poll() is None
            log_tail = list(self.log)
            return {
                "running": running,
                "master_status": _master_status(running, self.last_error, log_tail),
                "pid": self.process.pid if running and self.process is not None else None,
                "interface": self.interface,
                "started_at": self.started_at,
                "stopped_at": self.stopped_at,
                "uptime_s": round(time.time() - self.started_at, 3)
                if running and self.started_at is not None
                else None,
                "last_returncode": self.last_returncode,
                "last_error": self.last_error,
                "log_tail": log_tail,
            }


@dataclass
class RuntimeParameter:
    """One Testknecht-generated process path accepted by the gateway.

    The gateway deliberately receives this reduced runtime description instead
    of vendor ESI XML.  Testknecht owns catalog parsing; the server owns local
    process-image state, subscriptions and backend command execution.
    """

    path: str
    access: str
    value_type: str
    safe_value: Any
    metadata: dict[str, Any]

    @classmethod
    def from_payload(cls, payload: dict[str, Any]) -> "RuntimeParameter":
        path = str(payload.get("path") or "").strip()
        if not path:
            raise ValueError("Runtime parameter is missing path.")
        access = str(payload.get("access") or "read").strip().lower()
        if access not in {"read", "write", "read_write"}:
            raise ValueError(f"Runtime parameter {path!r} has invalid access {access!r}.")
        value_type = str(payload.get("value_type") or payload.get("type") or "object").strip().lower()
        return cls(
            path=path,
            access=access,
            value_type=value_type,
            safe_value=_default_safe_value(payload, value_type),
            metadata=dict(payload),
        )

    @property
    def readable(self) -> bool:
        return self.access in {"read", "read_write"}

    @property
    def writable(self) -> bool:
        return self.access in {"write", "read_write"}


@dataclass
class RuntimeConfig:
    """Effective gateway configuration generated by Testknecht."""

    raw: dict[str, Any] = field(default_factory=dict)
    parameters: dict[str, RuntimeParameter] = field(default_factory=dict)
    terminals: list[dict[str, Any]] = field(default_factory=list)
    missing_descriptions: list[dict[str, Any]] = field(default_factory=list)
    configured_at: float | None = None

    @classmethod
    def from_payload(cls, payload: dict[str, Any]) -> "RuntimeConfig":
        catalog = payload.get("catalog") if isinstance(payload.get("catalog"), dict) else {}
        parameters_payload = catalog.get("parameters") or payload.get("parameters") or []
        if not isinstance(parameters_payload, list):
            raise ValueError("Runtime config catalog.parameters must be a list.")
        parameters = [RuntimeParameter.from_payload(row) for row in parameters_payload if isinstance(row, dict)]
        terminals_payload = payload.get("inventory") or payload.get("terminals") or catalog.get("terminals") or []
        missing_payload = catalog.get("missing_descriptions") or payload.get("missing_descriptions") or []
        return cls(
            raw=dict(payload),
            parameters={parameter.path: parameter for parameter in parameters},
            terminals=[dict(row) for row in terminals_payload if isinstance(row, dict)],
            missing_descriptions=[dict(row) for row in missing_payload if isinstance(row, dict)],
            configured_at=time.time(),
        )

    def as_dict(self) -> dict[str, Any]:
        return {
            "configured": self.configured_at is not None,
            "configured_at": self.configured_at,
            "parameter_count": len(self.parameters),
            "parameters": [parameter.metadata for parameter in self.parameters.values()],
            "terminals": self.terminals,
            "missing_descriptions": self.missing_descriptions,
            "catalog_source": "testknecht_runtime_config",
        }


@dataclass
class Subscription:
    id: str
    paths: set[str]
    mode: str = "change"
    deadband: float | None = None
    min_interval_s: float = 0.0
    created_at: float = field(default_factory=time.time)
    last_emit_by_path: dict[str, float] = field(default_factory=dict)

    @classmethod
    def from_payload(cls, payload: dict[str, Any], known_paths: set[str]) -> "Subscription":
        raw_paths = payload.get("paths") or payload.get("path") or []
        if isinstance(raw_paths, str):
            raw_paths = [raw_paths]
        paths = {str(path).strip() for path in raw_paths if str(path).strip()}
        unknown = sorted(paths - known_paths)
        if unknown:
            raise ValueError(f"Subscription contains unknown EtherCAT path(s): {', '.join(unknown)}")
        if not paths:
            raise ValueError("Subscription needs at least one known path.")
        deadband = payload.get("deadband")
        return cls(
            id=str(payload.get("id") or uuid4()),
            paths=paths,
            mode=str(payload.get("mode") or "change"),
            deadband=float(deadband) if deadband is not None else None,
            min_interval_s=float(payload.get("min_interval_s") or 0.0),
        )

    def should_emit(self, path: str, old_value: Any, new_value: Any) -> bool:
        if path not in self.paths:
            return False
        now = time.time()
        last_emit = self.last_emit_by_path.get(path)
        if last_emit is not None and (now - last_emit) < self.min_interval_s:
            return False
        if self.deadband is not None and _numeric(old_value) and _numeric(new_value):
            if abs(float(new_value) - float(old_value)) < self.deadband:
                return False
        changed = old_value != new_value
        if self.mode in {"change", "edge"} and not changed:
            return False
        self.last_emit_by_path[path] = now
        return True


class SoemGateway:
    def __init__(self, config: GatewayConfig) -> None:
        self.config = config
        self.state = MasterState(interface=config.interface)
        self.runtime = RuntimeConfig()
        self.process_values: dict[str, Any] = {}
        self.subscriptions: dict[str, Subscription] = {}
        self.events: deque[dict[str, Any]] = deque(maxlen=1000)
        self.runtime_lock = threading.RLock()

    def health(self) -> dict[str, Any]:
        return {
            "status": "PASS",
            "ok": True,
            "message": "SOEM Python gateway is running.",
            "interface": self.config.interface,
            "simple_ng": str(self.config.simple_ng),
            "slaveinfo": str(self.config.slaveinfo),
            "runtime_configured": self.runtime.configured_at is not None,
        }

    def identity(self) -> dict[str, Any]:
        return {
            "ok": True,
            "status": "PASS",
            "gateway": "soem-python-gateway",
            "backend": "external_soem_cli",
            "license_boundary": "SOEM is supervised as an external executable.",
            "simple_ng": str(self.config.simple_ng),
            "slaveinfo": str(self.config.slaveinfo),
        }

    def adapters(self) -> dict[str, Any]:
        result = self._run_command([str(self.config.slaveinfo)], sudo=False)
        return {
            "status": "PASS" if result["returncode"] == 0 else "FAIL",
            "command": result["command"],
            "returncode": result["returncode"],
            "adapters": _parse_adapters(result["stdout"]),
            "stdout": result["stdout"],
            "stderr": result["stderr"],
        }

    def inventory(self, interface: str | None = None) -> dict[str, Any]:
        selected = self._resolve_interface(interface)
        result = self._run_command(
            [str(self.config.slaveinfo), selected],
            sudo=self.config.inventory_with_sudo,
        )
        inventory_ok = result["returncode"] == 0 and not _slaveinfo_has_error(result["stdout"], result["stderr"])
        return {
            "status": "PASS" if inventory_ok else "FAIL",
            "interface": selected,
            "command": result["command"],
            "returncode": result["returncode"],
            "slave_count": _parse_slave_count(result["stdout"]),
            "slaves": _parse_slaveinfo(result["stdout"]),
            "stdout": result["stdout"],
            "stderr": result["stderr"],
        }

    def request_config(self, payload: dict[str, Any]) -> dict[str, Any]:
        runtime = RuntimeConfig.from_payload(payload)
        with self.runtime_lock:
            self.runtime = runtime
            self.process_values = {
                path: self.process_values.get(path, _initial_value(parameter))
                for path, parameter in runtime.parameters.items()
            }
            self.subscriptions.clear()
            self.events.clear()
            self._append_event_locked(
                "gateway.configured",
                None,
                True,
                quality="good" if runtime.parameters else "empty_catalog",
                reason="request_config",
            )
        data = runtime.as_dict()
        return {
            "ok": True,
            "status": "WARN" if runtime.missing_descriptions else "PASS",
            "message": "Runtime EtherCAT configuration accepted.",
            "data": data,
        }

    def catalog(self) -> dict[str, Any]:
        with self.runtime_lock:
            return {"ok": True, "status": "PASS", **self.runtime.as_dict()}

    def read(self, path: str) -> dict[str, Any]:
        with self.runtime_lock:
            parameter = self._require_parameter(path)
            if not parameter.readable and not parameter.writable:
                raise ValueError(f"EtherCAT path {path!r} is not readable.")
            return {
                "ok": True,
                "status": "PASS",
                "path": path,
                "value": self.process_values.get(path, _initial_value(parameter)),
                "quality": "cached_process_image",
                "metadata": parameter.metadata,
            }

    def read_many(self, payload: dict[str, Any]) -> dict[str, Any]:
        raw_paths = payload.get("paths") or []
        if not isinstance(raw_paths, list):
            raise ValueError("read-many payload needs paths as a list.")
        values = [self.read(str(path)) for path in raw_paths]
        return {"ok": True, "status": "PASS", "values": values}

    def write(self, payload: dict[str, Any]) -> dict[str, Any]:
        path = str(payload.get("path") or "").strip()
        if not path:
            raise ValueError("write payload needs path.")
        if "value" not in payload:
            raise ValueError("write payload needs value.")
        value = payload["value"]
        with self.runtime_lock:
            parameter = self._require_parameter(path)
            if not parameter.writable:
                raise ValueError(f"EtherCAT path {path!r} is not writable.")
            coerced = _coerce_value(value, parameter.value_type)
            old_value = self.process_values.get(path, _initial_value(parameter))
            self.process_values[path] = coerced
            emitted = self._emit_value_change_locked(path, old_value, coerced, reason="write")
            return {
                "ok": True,
                "status": "PASS",
                "path": path,
                "value": coerced,
                "old_value": old_value,
                "events_emitted": emitted,
                "quality": "cached_process_image",
            }

    def safe_off(self) -> dict[str, Any]:
        changed: list[dict[str, Any]] = []
        with self.runtime_lock:
            for path, parameter in self.runtime.parameters.items():
                if not parameter.writable:
                    continue
                old_value = self.process_values.get(path, _initial_value(parameter))
                new_value = parameter.safe_value
                self.process_values[path] = new_value
                emitted = self._emit_value_change_locked(path, old_value, new_value, reason="safe_off")
                changed.append({"path": path, "old_value": old_value, "value": new_value, "events_emitted": emitted})
            self._append_event_locked("gateway.safe_off", None, True, quality="good", reason="safe_off")
        return {
            "ok": True,
            "status": "PASS",
            "message": "Safe-off values applied to writable runtime paths.",
            "changed": changed,
        }

    def snapshot(self) -> dict[str, Any]:
        with self.runtime_lock:
            return {
                "ok": True,
                "status": "PASS",
                "values": dict(self.process_values),
                "catalog": self.runtime.as_dict(),
                "event_count": len(self.events),
            }

    def create_subscription(self, payload: dict[str, Any]) -> dict[str, Any]:
        with self.runtime_lock:
            subscription = Subscription.from_payload(payload, set(self.runtime.parameters))
            self.subscriptions[subscription.id] = subscription
            return {
                "ok": True,
                "status": "PASS",
                "subscription": self._subscription_dict(subscription),
            }

    def list_subscriptions(self) -> dict[str, Any]:
        with self.runtime_lock:
            return {
                "ok": True,
                "status": "PASS",
                "subscriptions": [self._subscription_dict(item) for item in self.subscriptions.values()],
            }

    def cancel_subscription(self, subscription_id: str) -> dict[str, Any]:
        with self.runtime_lock:
            removed = self.subscriptions.pop(subscription_id, None)
            return {
                "ok": removed is not None,
                "status": "PASS" if removed is not None else "WARN",
                "message": "Subscription cancelled." if removed is not None else "Subscription was not active.",
                "subscription_id": subscription_id,
            }

    def events_for_subscription(self, subscription_id: str | None = None, since: int | None = None) -> dict[str, Any]:
        with self.runtime_lock:
            events = list(self.events)
            if subscription_id:
                if subscription_id not in self.subscriptions:
                    raise ValueError(f"Unknown subscription {subscription_id!r}.")
                events = [event for event in events if event.get("subscription_id") == subscription_id]
            if since is not None:
                events = [event for event in events if int(event.get("sequence", 0)) > since]
            return {"ok": True, "status": "PASS", "events": events, "event_count": len(events)}

    def start(self, interface: str | None = None) -> dict[str, Any]:
        selected = self._resolve_interface(interface)
        with self.state.lock:
            if self.state.process is not None and self.state.process.poll() is None:
                return {
                    "status": "PASS",
                    "message": "SOEM master is already running.",
                    **self.state.status(),
                }

            command = [str(self.config.simple_ng), selected]
            if self.config.start_with_sudo:
                command = ["sudo", *command]

            try:
                process = subprocess.Popen(
                    command,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                    bufsize=1,
                )
            except OSError as exc:
                self.state.last_error = str(exc)
                return {"status": "FAIL", "message": str(exc), "command": command}

            self.state.process = process
            self.state.interface = selected
            self.state.started_at = time.time()
            self.state.stopped_at = None
            self.state.last_returncode = None
            self.state.last_error = None
            self.state.log.clear()
            threading.Thread(target=self._collect_output, args=(process,), daemon=True).start()

        time.sleep(0.2)
        current_status = self.state.status()
        if not current_status["running"] and current_status["master_status"] == "FAILED":
            return {
                "status": "FAIL",
                "message": "SOEM master process exited during startup.",
                "command": command,
                **current_status,
            }

        return {
            "status": "PASS",
            "message": "SOEM master process started.",
            "command": command,
            **current_status,
        }

    def stop(self, timeout_s: float = 3.0) -> dict[str, Any]:
        with self.state.lock:
            process = self.state.process
            if process is None or process.poll() is not None:
                self.state.process = None
                self.state.stopped_at = time.time()
                return {
                    "status": "PASS",
                    "message": "SOEM master is not running.",
                    **self.state.status(),
                }

            process.send_signal(signal.SIGTERM)

        try:
            process.wait(timeout=timeout_s)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait(timeout=timeout_s)

        with self.state.lock:
            self.state.last_returncode = process.returncode
            self.state.process = None
            self.state.stopped_at = time.time()

        return {
            "status": "PASS",
            "ok": True,
            "message": "SOEM master process stopped.",
            **self.state.status(),
        }

    def pause(self) -> dict[str, Any]:
        # The CLI-backed prototype has no pause primitive yet. Returning a
        # visible WARN keeps the API shape stable without pretending to affect
        # the external master cycle.
        return {
            "ok": True,
            "status": "WARN",
            "message": "Pause is accepted by the gateway API but not implemented by the CLI backend.",
            **self.state.status(),
        }

    def _collect_output(self, process: subprocess.Popen[str]) -> None:
        assert process.stdout is not None
        for line in process.stdout:
            self.state.append_log(line)

        returncode = process.wait()
        with self.state.lock:
            self.state.last_returncode = returncode
            if self.state.process is process:
                self.state.process = None
                self.state.stopped_at = time.time()

    def _run_command(self, command: list[str], sudo: bool) -> dict[str, Any]:
        full_command = ["sudo", *command] if sudo else command
        try:
            completed = subprocess.run(full_command, capture_output=True, text=True, timeout=30)
        except (OSError, subprocess.TimeoutExpired) as exc:
            return {
                "command": full_command,
                "returncode": None,
                "stdout": "",
                "stderr": str(exc),
            }
        return {
            "command": full_command,
            "returncode": completed.returncode,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
        }

    def _resolve_interface(self, interface: str | None) -> str:
        runtime_master = self.runtime.raw.get("master") if isinstance(self.runtime.raw.get("master"), dict) else {}
        selected = interface or self.runtime.raw.get("interface") or runtime_master.get("interface") or self.config.interface
        if not selected:
            raise ValueError("No EtherCAT interface configured. Pass ?interface=<ifname> or --interface.")
        return str(selected)

    def _require_parameter(self, path: str) -> RuntimeParameter:
        if not self.runtime.parameters:
            raise ValueError("No runtime EtherCAT configuration loaded. Call /ethercat/request-config first.")
        parameter = self.runtime.parameters.get(path)
        if parameter is None:
            raise ValueError(f"Unknown EtherCAT path {path!r}.")
        return parameter

    def _emit_value_change_locked(self, path: str, old_value: Any, new_value: Any, reason: str) -> int:
        emitted = 0
        for subscription in self.subscriptions.values():
            if not subscription.should_emit(path, old_value, new_value):
                continue
            self._append_event_locked(
                path,
                old_value,
                new_value,
                quality="cached_process_image",
                reason=reason,
                subscription_id=subscription.id,
            )
            emitted += 1
        return emitted

    def _append_event_locked(
        self,
        path: str,
        old_value: Any,
        new_value: Any,
        *,
        quality: str,
        reason: str,
        subscription_id: str | None = None,
    ) -> None:
        self.events.append(
            {
                "sequence": len(self.events) + 1,
                "timestamp": time.time(),
                "path": path,
                "old_value": old_value,
                "value": new_value,
                "quality": quality,
                "reason": reason,
                "subscription_id": subscription_id,
                "master_status": self.state.status()["master_status"],
            }
        )

    @staticmethod
    def _subscription_dict(subscription: Subscription) -> dict[str, Any]:
        return {
            "id": subscription.id,
            "paths": sorted(subscription.paths),
            "mode": subscription.mode,
            "deadband": subscription.deadband,
            "min_interval_s": subscription.min_interval_s,
            "created_at": subscription.created_at,
        }


class GatewayHandler(BaseHTTPRequestHandler):
    gateway: SoemGateway

    def do_GET(self) -> None:  # noqa: N802 - http.server API name
        parsed = urlparse(self.path)
        query = parse_qs(parsed.query)
        try:
            if parsed.path in {"/health", "/ethercat/health"}:
                self._json(self.gateway.health())
            elif parsed.path == "/identity":
                self._json(self.gateway.identity())
            elif parsed.path in {"/status", "/ethercat/master/status", "/ethercat/status"}:
                self._json({"ok": True, "status": "PASS", **self.gateway.state.status()})
            elif parsed.path in {"/adapters", "/ethercat/adapters"}:
                self._json(self.gateway.adapters())
            elif parsed.path in {"/inventory", "/ethercat/inventory"}:
                self._json(self.gateway.inventory(_first(query, "interface")))
            elif parsed.path in {"/logs", "/ethercat/master/log", "/ethercat/logs"}:
                log_tail = self.gateway.state.status()["log_tail"]
                tail = _first(query, "tail")
                if tail and tail.isdigit():
                    log_tail = log_tail[-int(tail) :]
                self._json({"ok": True, "status": "PASS", "log_tail": log_tail})
            elif parsed.path == "/ethercat/catalog":
                self._json(self.gateway.catalog())
            elif parsed.path == "/ethercat/snapshot":
                self._json(self.gateway.snapshot())
            elif parsed.path == "/ethercat/read":
                path = _first(query, "path")
                if not path:
                    raise ValueError("/ethercat/read requires ?path=<normalized-path>.")
                self._json(self.gateway.read(path))
            elif parsed.path.startswith("/ethercat/slave/") and parsed.path.endswith("/sdo"):
                self._json(
                    {
                        "ok": False,
                        "status": "WARN",
                        "message": "SDO access is part of the gateway API contract but not implemented by the CLI backend.",
                    }
                )
            elif parsed.path == "/ethercat/subscriptions":
                self._json(self.gateway.list_subscriptions())
            elif parsed.path == "/ethercat/events":
                since_raw = _first(query, "since")
                since = int(since_raw) if since_raw and since_raw.isdigit() else None
                self._json(self.gateway.events_for_subscription(_first(query, "subscription"), since=since))
            elif parsed.path == "/ethercat/events/stream":
                self._event_stream(_first(query, "subscription"))
            else:
                self._json({"status": "FAIL", "message": f"Unknown endpoint: {parsed.path}"}, HTTPStatus.NOT_FOUND)
        except ValueError as exc:
            self._json({"status": "FAIL", "message": str(exc)}, HTTPStatus.BAD_REQUEST)

    def do_POST(self) -> None:  # noqa: N802 - http.server API name
        parsed = urlparse(self.path)
        query = parse_qs(parsed.query)
        try:
            payload = self._read_json_body()
            if parsed.path in {"/start", "/ethercat/master/start", "/ethercat/processdata/start"}:
                self._json(self.gateway.start(_first(query, "interface")))
            elif parsed.path in {"/stop", "/ethercat/master/stop", "/ethercat/processdata/stop"}:
                self._json(self.gateway.stop())
            elif parsed.path == "/ethercat/master/pause":
                self._json(self.gateway.pause())
            elif parsed.path in {"/ethercat/request-config", "/ethercat/master/config-map"}:
                self._json(self.gateway.request_config(payload))
            elif parsed.path == "/ethercat/master/open":
                self._json({"ok": True, "status": "PASS", "message": "Interface accepted.", "interface": self.gateway._resolve_interface(_first(query, "interface") or payload.get("interface"))})
            elif parsed.path == "/ethercat/master/config-init":
                self._json(self.gateway.inventory(_first(query, "interface") or payload.get("interface")))
            elif parsed.path == "/ethercat/probe-inventory":
                self._json(self.gateway.inventory(str(payload.get("interface") or "") or _first(query, "interface")))
            elif parsed.path == "/ethercat/read-many":
                self._json(self.gateway.read_many(payload))
            elif parsed.path == "/ethercat/write":
                self._json(self.gateway.write(payload))
            elif parsed.path == "/ethercat/processdata/exchange":
                self._json(self.gateway.snapshot())
            elif parsed.path == "/ethercat/safe-off":
                self._json(self.gateway.safe_off())
            elif parsed.path.startswith("/ethercat/slave/") and parsed.path.endswith("/sdo"):
                self._json(
                    {
                        "ok": False,
                        "status": "WARN",
                        "message": "SDO access is part of the gateway API contract but not implemented by the CLI backend.",
                    }
                )
            elif parsed.path == "/ethercat/subscriptions":
                self._json(self.gateway.create_subscription(payload))
            elif parsed.path.startswith("/ethercat/subscriptions/") and parsed.path.endswith("/cancel"):
                subscription_id = parsed.path.removeprefix("/ethercat/subscriptions/").removesuffix("/cancel")
                self._json(self.gateway.cancel_subscription(subscription_id))
            else:
                self._json({"status": "FAIL", "message": f"Unknown endpoint: {parsed.path}"}, HTTPStatus.NOT_FOUND)
        except ValueError as exc:
            self._json({"status": "FAIL", "message": str(exc)}, HTTPStatus.BAD_REQUEST)

    def log_message(self, fmt: str, *args: Any) -> None:
        sys.stderr.write("[soem-gateway] " + fmt % args + "\n")

    def _json(self, payload: dict[str, Any], status: HTTPStatus = HTTPStatus.OK) -> None:
        data = json.dumps(payload, indent=2, sort_keys=True).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def _event_stream(self, subscription_id: str | None) -> None:
        payload = self.gateway.events_for_subscription(subscription_id)
        data = "".join(f"event: ethercat\ndata: {json.dumps(event, sort_keys=True)}\n\n" for event in payload["events"])
        encoded = data.encode("utf-8")
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Content-Length", str(len(encoded)))
        self.end_headers()
        self.wfile.write(encoded)

    def _read_json_body(self) -> dict[str, Any]:
        length = int(self.headers.get("Content-Length") or 0)
        if length <= 0:
            return {}
        raw = self.rfile.read(length).decode("utf-8")
        if not raw.strip():
            return {}
        data = json.loads(raw)
        if not isinstance(data, dict):
            raise ValueError("JSON request body must be an object.")
        return data


def _first(query: dict[str, list[str]], key: str) -> str | None:
    values = query.get(key)
    if not values:
        return None
    value = values[0].strip()
    return value or None


def _default_safe_value(payload: dict[str, Any], value_type: str) -> Any:
    if "safe_value" in payload:
        return _coerce_value(payload["safe_value"], value_type)
    if value_type == "bool":
        return False
    if value_type in {"int", "uint", "integer"}:
        return 0
    if value_type in {"float", "real"}:
        return 0.0
    return None


def _initial_value(parameter: RuntimeParameter) -> Any:
    if parameter.readable and not parameter.writable:
        return _default_safe_value(parameter.metadata, parameter.value_type)
    return parameter.safe_value


def _coerce_value(value: Any, value_type: str) -> Any:
    normalized = value_type.lower()
    if normalized == "bool":
        if isinstance(value, str):
            return value.strip().lower() in {"1", "true", "yes", "on", "high"}
        return bool(value)
    if normalized in {"int", "uint", "integer"}:
        return int(value)
    if normalized in {"float", "real"}:
        return float(value)
    return value


def _numeric(value: Any) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def _parse_adapters(stdout: str) -> list[dict[str, str]]:
    adapters = []
    for line in stdout.splitlines():
        stripped = line.strip()
        if not stripped.startswith("- "):
            continue
        item = stripped[2:].strip()
        if "  (" in item and item.endswith(")"):
            name, desc = item[:-1].split("  (", 1)
        else:
            name, desc = item, item
        adapters.append({"name": name.strip(), "description": desc.strip()})
    return adapters


def _parse_slave_count(stdout: str) -> int | None:
    for line in stdout.splitlines():
        stripped = line.strip()
        if stripped.endswith("slaves found and configured."):
            first = stripped.split(maxsplit=1)[0]
            if first.isdigit():
                return int(first)
        if stripped == "No slaves found!":
            return 0
    return None


def _slaveinfo_has_error(stdout: str, stderr: str) -> bool:
    combined = f"{stdout}\n{stderr}".lower()
    return _text_has_soem_error(combined)


def _text_has_soem_error(text: str) -> bool:
    combined = text.lower()
    error_markers = (
        "no socket connection",
        "excecute as root",
        "execute as root",
        "no slaves found",
        "error",
        "timeout",
    )
    return any(marker in combined for marker in error_markers)


def _master_status(running: bool, last_error: str | None, log_tail: list[str]) -> str:
    if running:
        return "RUNNING"
    if last_error:
        return "FAILED"
    if _text_has_soem_error("\n".join(log_tail)):
        return "FAILED"
    return "STOPPED"


def _parse_slaveinfo(stdout: str) -> list[dict[str, str]]:
    slaves: list[dict[str, str]] = []
    current: dict[str, str] | None = None
    for line in stdout.splitlines():
        stripped = line.strip()
        if stripped.startswith("Slave:"):
            if current:
                slaves.append(current)
            current = {"slot": stripped.split(":", 1)[1].strip()}
        elif current and ":" in stripped:
            key, value = stripped.split(":", 1)
            normalized = key.lower().strip().replace(" ", "_").replace(".", "")
            current[normalized] = value.strip()
    if current:
        slaves.append(current)
    return slaves


def _default_binary(name: str) -> Path:
    root = Path(__file__).resolve().parents[2]
    candidates = [
        root / "build" / "darwin-arm64" / "bin" / name,
        root / "build" / "darwin-x86_64" / "bin" / name,
        root / "build" / "default" / "bin" / name,
        root / "build-darwin" / "samples" / name / name,
        root / "build-darwin-x86_64" / "samples" / name / name,
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def _parse_args(argv: list[str]) -> GatewayConfig:
    parser = argparse.ArgumentParser(description="Expose SOEM sample executables through a small HTTP gateway.")
    parser.add_argument("--interface", help="EtherCAT network interface, for example en6 or eth0.")
    parser.add_argument("--host", default="127.0.0.1", help="HTTP bind host.")
    parser.add_argument("--port", type=int, default=8765, help="HTTP bind port.")
    parser.add_argument("--simple-ng", type=Path, default=_default_binary("simple_ng"), help="Path to simple_ng executable.")
    parser.add_argument("--slaveinfo", type=Path, default=_default_binary("slaveinfo"), help="Path to slaveinfo executable.")
    parser.add_argument("--log-lines", type=int, default=DEFAULT_LOG_LINES, help="Number of master log lines to keep.")
    parser.add_argument("--start-with-sudo", action="store_true", help="Start simple_ng through sudo.")
    parser.add_argument("--inventory-with-sudo", action="store_true", help="Run slaveinfo inventory through sudo.")
    args = parser.parse_args(argv)
    return GatewayConfig(
        interface=args.interface,
        host=args.host,
        port=args.port,
        simple_ng=args.simple_ng,
        slaveinfo=args.slaveinfo,
        log_lines=args.log_lines,
        start_with_sudo=args.start_with_sudo,
        inventory_with_sudo=args.inventory_with_sudo,
    )


def main(argv: list[str] | None = None) -> int:
    config = _parse_args(sys.argv[1:] if argv is None else argv)
    gateway = SoemGateway(config)
    gateway.state.log = deque(maxlen=config.log_lines)

    handler = type("ConfiguredGatewayHandler", (GatewayHandler,), {"gateway": gateway})
    server = ThreadingHTTPServer((config.host, config.port), handler)
    print(f"SOEM gateway listening on http://{config.host}:{config.port}")
    print(f"slaveinfo={config.slaveinfo}")
    print(f"simple_ng={config.simple_ng}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        gateway.stop()
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
