#!/usr/bin/env python3
"""Small HTTP gateway around SOEM sample executables.

The gateway intentionally supervises external SOEM binaries instead of linking
SOEM into Python. That keeps the boundary explicit: SOEM owns EtherCAT/BPF
access, while this script exposes a simple process-control and status API that
can be driven by Testknecht or other automation tools.

It is deliberately a dumb transport: it keeps a cached process image, a raw SDO
value store and subscriptions, but no ESI parsing, object names, types or access
policy — those live on the automation host. See the structured documentation in
``docs/`` (``docs/gateway/`` for install/usage/HTTP API, ``docs/concepts/`` for
the boundary and SDO transport split, ``docs/ports/`` for the macOS BPF backend).
"""

from __future__ import annotations

import argparse
import json
import os
import re
import signal
import subprocess
import sys
import threading
import time
from collections import deque
from dataclasses import dataclass, field
from http import HTTPStatus
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any
from urllib.parse import parse_qs, urlparse
from uuid import uuid4


DEFAULT_LOG_LINES = 300


@dataclass
class GatewayConfig:
    interface: str | None
    host: str
    port: int
    simple_ng: Path
    slaveinfo: Path
    pdo_server: Path
    log_lines: int
    start_with_sudo: bool
    inventory_with_sudo: bool


@dataclass
class MasterState:
    interface: str | None = None
    process: subprocess.Popen[str] | None = None
    started_at: float | None = None
    stopped_at: float | None = None
    last_returncode: int | None = None
    last_error: str | None = None
    log: deque[str] = field(default_factory=lambda: deque(maxlen=DEFAULT_LOG_LINES))
    lock: threading.RLock = field(default_factory=threading.RLock)

    def append_log(self, line: str) -> None:
        with self.lock:
            self.log.append(line.rstrip("\n"))

    def status(self) -> dict[str, Any]:
        with self.lock:
            running = self.process is not None and self.process.poll() is None
            log_tail = list(self.log)
            return {
                "running": running,
                "master_status": _master_status(running, self.last_error, log_tail),
                "pid": self.process.pid if running and self.process is not None else None,
                "interface": self.interface,
                "started_at": self.started_at,
                "stopped_at": self.stopped_at,
                "uptime_s": round(time.time() - self.started_at, 3)
                if running and self.started_at is not None
                else None,
                "last_returncode": self.last_returncode,
                "last_error": self.last_error,
                "log_tail": log_tail,
            }


@dataclass
class RuntimeParameter:
    """One Testknecht-generated process path accepted by the gateway.

    The gateway deliberately receives this reduced runtime description instead
    of vendor ESI XML.  Testknecht owns catalog parsing; the server owns local
    process-image state, subscriptions and backend command execution.
    """

    path: str
    access: str
    value_type: str
    safe_value: Any
    metadata: dict[str, Any]

    @classmethod
    def from_payload(cls, payload: dict[str, Any]) -> "RuntimeParameter":
        path = str(payload.get("path") or "").strip()
        if not path:
            raise ValueError("Runtime parameter is missing path.")
        access = str(payload.get("access") or "read").strip().lower()
        if access not in {"read", "write", "read_write"}:
            raise ValueError(f"Runtime parameter {path!r} has invalid access {access!r}.")
        value_type = str(payload.get("value_type") or payload.get("type") or "object").strip().lower()
        return cls(
            path=path,
            access=access,
            value_type=value_type,
            safe_value=_default_safe_value(payload, value_type),
            metadata=dict(payload),
        )

    @property
    def readable(self) -> bool:
        return self.access in {"read", "read_write"}

    @property
    def writable(self) -> bool:
        return self.access in {"write", "read_write"}


@dataclass
class RuntimeConfig:
    """Effective gateway configuration generated by Testknecht."""

    raw: dict[str, Any] = field(default_factory=dict)
    parameters: dict[str, RuntimeParameter] = field(default_factory=dict)
    terminals: list[dict[str, Any]] = field(default_factory=list)
    missing_descriptions: list[dict[str, Any]] = field(default_factory=list)
    configured_at: float | None = None

    @classmethod
    def from_payload(cls, payload: dict[str, Any]) -> "RuntimeConfig":
        catalog = payload.get("catalog") if isinstance(payload.get("catalog"), dict) else {}
        parameters_payload = catalog.get("parameters") or payload.get("parameters") or []
        if not isinstance(parameters_payload, list):
            raise ValueError("Runtime config catalog.parameters must be a list.")
        parameters = [RuntimeParameter.from_payload(row) for row in parameters_payload if isinstance(row, dict)]
        terminals_payload = payload.get("inventory") or payload.get("terminals") or catalog.get("terminals") or []
        missing_payload = catalog.get("missing_descriptions") or payload.get("missing_descriptions") or []
        return cls(
            raw=dict(payload),
            parameters={parameter.path: parameter for parameter in parameters},
            terminals=[dict(row) for row in terminals_payload if isinstance(row, dict)],
            missing_descriptions=[dict(row) for row in missing_payload if isinstance(row, dict)],
            configured_at=time.time(),
        )

    def as_dict(self) -> dict[str, Any]:
        return {
            "configured": self.configured_at is not None,
            "configured_at": self.configured_at,
            "parameter_count": len(self.parameters),
            "parameters": [parameter.metadata for parameter in self.parameters.values()],
            "terminals": self.terminals,
            "missing_descriptions": self.missing_descriptions,
            "catalog_source": "testknecht_runtime_config",
        }


@dataclass
class Subscription:
    id: str
    paths: set[str]
    mode: str = "change"
    deadband: float | None = None
    min_interval_s: float = 0.0
    created_at: float = field(default_factory=time.time)
    last_emit_by_path: dict[str, float] = field(default_factory=dict)

    @classmethod
    def from_payload(cls, payload: dict[str, Any], known_paths: set[str]) -> "Subscription":
        raw_paths = payload.get("paths") or payload.get("path") or []
        if isinstance(raw_paths, str):
            raw_paths = [raw_paths]
        paths = {str(path).strip() for path in raw_paths if str(path).strip()}
        unknown = sorted(paths - known_paths)
        if unknown:
            raise ValueError(f"Subscription contains unknown EtherCAT path(s): {', '.join(unknown)}")
        if not paths:
            raise ValueError("Subscription needs at least one known path.")
        deadband = payload.get("deadband")
        return cls(
            id=str(payload.get("id") or uuid4()),
            paths=paths,
            mode=str(payload.get("mode") or "change"),
            deadband=float(deadband) if deadband is not None else None,
            min_interval_s=float(payload.get("min_interval_s") or 0.0),
        )

    def should_emit(self, path: str, old_value: Any, new_value: Any) -> bool:
        if path not in self.paths:
            return False
        now = time.time()
        last_emit = self.last_emit_by_path.get(path)
        if last_emit is not None and (now - last_emit) < self.min_interval_s:
            return False
        if self.deadband is not None and _numeric(old_value) and _numeric(new_value):
            if abs(float(new_value) - float(old_value)) < self.deadband:
                return False
        changed = old_value != new_value
        if self.mode in {"change", "edge"} and not changed:
            return False
        self.last_emit_by_path[path] = now
        return True


class ProcessDataServer:
    """Drives the external ``soem_pdo_server`` for real per-path process data.

    Unlike ``simple_ng`` (a one-way demo that only prints iterations), the
    ``soem_pdo_server`` sample is a real cyclic EtherCAT master with a line
    protocol on stdin/stdout: it brings the bus to OPERATIONAL and then answers
    ``READ``/``WRITE``/``SAFE_OFF``/``STATUS``/``STOP`` with one JSON line each.
    Read/write address the process image by ``byte``/``bit`` offset, which the
    Testknecht-generated runtime catalog already carries. This keeps the gateway
    dumb (no naming/typing) while doing genuine hardware I/O.
    """

    def __init__(self, binary: Path, *, start_with_sudo: bool = False, timeout_s: float = 5.0) -> None:
        self.binary = binary
        self.start_with_sudo = start_with_sudo
        self.timeout_s = float(timeout_s)
        self.process: subprocess.Popen[str] | None = None
        self.bringup: dict[str, Any] = {}
        self.lock = threading.RLock()

    def available(self) -> bool:
        try:
            return bool(self.binary) and Path(self.binary).exists()
        except OSError:
            return False

    def is_running(self) -> bool:
        return self.process is not None and self.process.poll() is None

    def start(self, interface: str) -> dict[str, Any]:
        with self.lock:
            if self.is_running():
                return {"ok": True, "status": "PASS", "message": "Process-data master already running.", **self.bringup}
            command = [str(self.binary), interface]
            if self.start_with_sudo:
                command = ["sudo", *command]
            try:
                # stderr -> devnull keeps the stdout JSON channel clean of SOEM
                # library diagnostics so responses stay parseable.
                self.process = subprocess.Popen(
                    command,
                    stdin=subprocess.PIPE,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.DEVNULL,
                    text=True,
                    bufsize=1,
                )
            except OSError as exc:
                self.process = None
                return {"ok": False, "status": "FAIL", "error": "pdo_start_failed", "message": str(exc), "command": command}
            # The helper prints one bring-up status line after reaching
            # OPERATIONAL (or a JSON error if init/slaves/operational failed).
            self.bringup = _parse_pdo_line(self._readline())
            if not self.bringup.get("ok"):
                self._terminate()
                return {"ok": False, "status": "FAIL", "error": "pdo_bringup_failed", "message": "Process-data bring-up failed.", "bringup": self.bringup, "command": command}
            return {"ok": True, "status": "PASS", "message": "Process-data master running.", "command": command, **self.bringup}

    def read(self, path: str, byte: int, bit: int) -> dict[str, Any]:
        return self._command("READ", path, int(byte), int(bit))

    def write(self, path: str, byte: int, bit: int, value: Any) -> dict[str, Any]:
        return self._command("WRITE", path, int(byte), int(bit), 1 if _truthy_pdo(value) else 0)

    def safe_off(self) -> dict[str, Any]:
        return self._command("SAFE_OFF")

    def status(self) -> dict[str, Any]:
        return self._command("STATUS")

    def stop(self, timeout_s: float = 3.0) -> dict[str, Any]:
        with self.lock:
            process = self.process
            if process is None or process.poll() is not None:
                self.process = None
                return {"ok": True, "status": "PASS", "message": "Process-data master not running."}
            try:
                if process.stdin is not None:
                    process.stdin.write("STOP\n")
                    process.stdin.flush()
                    self._readline()  # consume the {"ok":true,"stopped":true} line
            except (OSError, ValueError):
                pass
        try:
            process.wait(timeout=timeout_s)
        except subprocess.TimeoutExpired:
            self._terminate()
        with self.lock:
            _close_streams(process)
            self.process = None
        return {"ok": True, "status": "PASS", "message": "Process-data master stopped."}

    def _command(self, *parts: Any) -> dict[str, Any]:
        with self.lock:
            process = self.process
            if process is None or process.poll() is not None or process.stdin is None:
                return {"ok": False, "status": "FAIL", "error": "pdo_not_running", "message": "Process-data master is not running."}
            line = " ".join(str(part) for part in parts)
            try:
                process.stdin.write(line + "\n")
                process.stdin.flush()
            except (OSError, ValueError) as exc:
                return {"ok": False, "status": "FAIL", "error": "pdo_write_failed", "message": str(exc)}
            return _parse_pdo_line(self._readline())

    def _readline(self) -> str:
        process = self.process
        if process is None or process.stdout is None:
            return ""
        return process.stdout.readline()

    def _terminate(self) -> None:
        process = self.process
        if process is None:
            return
        process.terminate()
        try:
            process.wait(timeout=self.timeout_s)
        except subprocess.TimeoutExpired:
            process.kill()
        _close_streams(process)
        self.process = None


def _close_streams(process: subprocess.Popen[str]) -> None:
    """Close a helper's stdin/stdout pipes to avoid leaking file descriptors."""

    for stream in (process.stdin, process.stdout):
        try:
            if stream is not None:
                stream.close()
        except OSError:
            pass


def _parse_pdo_line(line: str) -> dict[str, Any]:
    """Parse one JSON response line from soem_pdo_server."""

    text = (line or "").strip()
    if not text:
        return {"ok": False, "status": "FAIL", "error": "pdo_no_response", "message": "No response from process-data master."}
    try:
        data = json.loads(text)
    except json.JSONDecodeError:
        return {"ok": False, "status": "FAIL", "error": "pdo_invalid_response", "message": text[:200]}
    return data if isinstance(data, dict) else {"ok": False, "status": "FAIL", "error": "pdo_invalid_response"}


def _truthy_pdo(value: Any) -> bool:
    if isinstance(value, str):
        return value.strip().lower() in {"1", "true", "yes", "on", "high"}
    return bool(value)


def _process_offsets(parameter: "RuntimeParameter") -> tuple[int, int]:
    """Return the (byte, bit) process-image offset the host put in the catalog."""

    meta = parameter.metadata if isinstance(parameter.metadata, dict) else {}
    return int(meta.get("process_byte_offset", 0) or 0), int(meta.get("process_bit_offset", 0) or 0)


class SoemGateway:
    def __init__(self, config: GatewayConfig) -> None:
        self.config = config
        self.state = MasterState(interface=config.interface)
        self.runtime = RuntimeConfig()
        self.pdo = ProcessDataServer(config.pdo_server, start_with_sudo=config.start_with_sudo)
        self.process_values: dict[str, Any] = {}
        # Raw SDO value store keyed by slot, then (index, subindex). The gateway
        # is a dumb mailbox transport: it holds only raw values, no object names,
        # types or access policy (those live on the Testknecht host). The external
        # simple_ng sample does not expose CoE mailbox traffic yet, so reads round
        # trip prior writes and a real ecx_SDO backend can replace this store.
        self.sdo_raw: dict[int, dict[tuple[int, int], Any]] = {}
        self.subscriptions: dict[str, Subscription] = {}
        self.events: deque[dict[str, Any]] = deque(maxlen=1000)
        self.runtime_lock = threading.RLock()

    def health(self) -> dict[str, Any]:
        return {
            "status": "PASS",
            "ok": True,
            "message": "SOEM Python gateway is running.",
            "interface": self.config.interface,
            "simple_ng": str(self.config.simple_ng),
            "slaveinfo": str(self.config.slaveinfo),
            "pdo_server": str(self.config.pdo_server),
            "process_data": "soem_pdo_server" if self.pdo.available() else "cached_image",
            "runtime_configured": self.runtime.configured_at is not None,
        }

    def identity(self) -> dict[str, Any]:
        return {
            "ok": True,
            "status": "PASS",
            "gateway": "soem-python-gateway",
            "backend": "external_soem_cli",
            "license_boundary": "SOEM is supervised as an external executable.",
            "process_data_backend": "soem_pdo_server" if self.pdo.available() else "cached_image",
            "simple_ng": str(self.config.simple_ng),
            "slaveinfo": str(self.config.slaveinfo),
            "pdo_server": str(self.config.pdo_server),
        }

    def adapters(self) -> dict[str, Any]:
        result = self._run_command([str(self.config.slaveinfo)], sudo=False)
        return {
            "status": "PASS" if result["returncode"] == 0 else "FAIL",
            "command": result["command"],
            "returncode": result["returncode"],
            "adapters": _parse_adapters(result["stdout"]),
            "stdout": result["stdout"],
            "stderr": result["stderr"],
        }

    def inventory(self, interface: str | None = None) -> dict[str, Any]:
        selected = self._resolve_interface(interface)
        result = self._run_command(
            [str(self.config.slaveinfo), selected],
            sudo=self.config.inventory_with_sudo,
        )
        inventory_ok = result["returncode"] == 0 and not _slaveinfo_has_error(result["stdout"], result["stderr"])
        return {
            "status": "PASS" if inventory_ok else "FAIL",
            "interface": selected,
            "command": result["command"],
            "returncode": result["returncode"],
            "slave_count": _parse_slave_count(result["stdout"]),
            "slaves": _parse_slaveinfo(result["stdout"]),
            "stdout": result["stdout"],
            "stderr": result["stderr"],
        }

    def request_config(self, payload: dict[str, Any]) -> dict[str, Any]:
        runtime = RuntimeConfig.from_payload(payload)
        with self.runtime_lock:
            self.runtime = runtime
            self.process_values = {
                path: self.process_values.get(path, _initial_value(parameter))
                for path, parameter in runtime.parameters.items()
            }
            self.subscriptions.clear()
            self.events.clear()
            self._append_event_locked(
                "gateway.configured",
                None,
                True,
                quality="good" if runtime.parameters else "empty_catalog",
                reason="request_config",
            )
        data = runtime.as_dict()
        return {
            "ok": True,
            "status": "WARN" if runtime.missing_descriptions else "PASS",
            "message": "Runtime EtherCAT configuration accepted.",
            "data": data,
        }

    def catalog(self) -> dict[str, Any]:
        with self.runtime_lock:
            return {"ok": True, "status": "PASS", **self.runtime.as_dict()}

    def read(self, path: str) -> dict[str, Any]:
        with self.runtime_lock:
            parameter = self._require_parameter(path)
            if not parameter.readable and not parameter.writable:
                raise ValueError(f"EtherCAT path {path!r} is not readable.")
            if self.pdo.is_running():
                # Real input bit from the live process image via soem_pdo_server.
                byte, bit = _process_offsets(parameter)
                response = self.pdo.read(path, byte, bit)
                if response.get("ok") and "value" in response:
                    self.process_values[path] = response["value"]
                    return {
                        "ok": True,
                        "status": "PASS",
                        "path": path,
                        "value": response["value"],
                        "input_byte": response.get("input_byte"),
                        "quality": "process_image",
                        "metadata": parameter.metadata,
                    }
                return {"ok": False, "status": "FAIL", "path": path, "quality": "process_image", **response}
            return {
                "ok": True,
                "status": "PASS",
                "path": path,
                "value": self.process_values.get(path, _initial_value(parameter)),
                "quality": "cached_process_image",
                "metadata": parameter.metadata,
            }

    def read_many(self, payload: dict[str, Any]) -> dict[str, Any]:
        raw_paths = payload.get("paths") or []
        if not isinstance(raw_paths, list):
            raise ValueError("read-many payload needs paths as a list.")
        values = [self.read(str(path)) for path in raw_paths]
        return {"ok": True, "status": "PASS", "values": values}

    def write(self, payload: dict[str, Any]) -> dict[str, Any]:
        path = str(payload.get("path") or "").strip()
        if not path:
            raise ValueError("write payload needs path.")
        if "value" not in payload:
            raise ValueError("write payload needs value.")
        value = payload["value"]
        with self.runtime_lock:
            parameter = self._require_parameter(path)
            if not parameter.writable:
                raise ValueError(f"EtherCAT path {path!r} is not writable.")
            coerced = _coerce_value(value, parameter.value_type)
            old_value = self.process_values.get(path, _initial_value(parameter))
            if self.pdo.is_running():
                # Real output bit on the live process image via soem_pdo_server.
                byte, bit = _process_offsets(parameter)
                response = self.pdo.write(path, byte, bit, coerced)
                if not response.get("ok"):
                    return {"ok": False, "status": "FAIL", "path": path, "quality": "process_image", **response}
                new_value = response.get("value", coerced)
                self.process_values[path] = new_value
                emitted = self._emit_value_change_locked(path, old_value, new_value, reason="write")
                return {
                    "ok": True,
                    "status": "PASS",
                    "path": path,
                    "value": new_value,
                    "old_value": old_value,
                    "events_emitted": emitted,
                    "output_byte": response.get("output_byte"),
                    "quality": "process_image",
                }
            self.process_values[path] = coerced
            emitted = self._emit_value_change_locked(path, old_value, coerced, reason="write")
            return {
                "ok": True,
                "status": "PASS",
                "path": path,
                "value": coerced,
                "old_value": old_value,
                "events_emitted": emitted,
                "quality": "cached_process_image",
            }

    def safe_off(self) -> dict[str, Any]:
        changed: list[dict[str, Any]] = []
        with self.runtime_lock:
            # Clear the real output image first when the master runs, then mirror
            # the safe values into the cached image and emit evidence.
            pdo_result = self.pdo.safe_off() if self.pdo.is_running() else None
            for path, parameter in self.runtime.parameters.items():
                if not parameter.writable:
                    continue
                old_value = self.process_values.get(path, _initial_value(parameter))
                new_value = parameter.safe_value
                self.process_values[path] = new_value
                emitted = self._emit_value_change_locked(path, old_value, new_value, reason="safe_off")
                changed.append({"path": path, "old_value": old_value, "value": new_value, "events_emitted": emitted})
            self._append_event_locked("gateway.safe_off", None, True, quality="good", reason="safe_off")
        result: dict[str, Any] = {
            "ok": True,
            "status": "PASS",
            "message": "Safe-off values applied to writable runtime paths.",
            "changed": changed,
        }
        if pdo_result is not None:
            result["pdo"] = pdo_result
            result["quality"] = "process_image"
        return result

    def snapshot(self) -> dict[str, Any]:
        with self.runtime_lock:
            return {
                "ok": True,
                "status": "PASS",
                "values": dict(self.process_values),
                "catalog": self.runtime.as_dict(),
                "event_count": len(self.events),
            }

    def sdo_read(self, slot: int, index: Any, subindex: Any = 0, value_type: str | None = None) -> dict[str, Any]:
        """Raw CoE SDO mailbox read.

        The gateway is dumb: it returns the raw value for ``(slot, index,
        subindex)`` and does not interpret object names, types or access. An
        object that was never written reads back as ``null`` (a real ``ecx_SDO``
        backend would fetch it from the slave). The host owns the SDO catalog.
        """

        index_int, subindex_int, index_hex, subindex_hex = _normalize_sdo_address(index, subindex)
        with self.runtime_lock:
            value = self.sdo_raw.get(int(slot), {}).get((index_int, subindex_int))
        return {
            "ok": True,
            "status": "PASS",
            "slot": int(slot),
            "index": index_hex,
            "subindex": subindex_hex,
            "value": value,
            "value_type": value_type,
        }

    def sdo_write(self, slot: int, index: Any, subindex: Any, value: Any, value_type: str | None = None) -> dict[str, Any]:
        """Raw CoE SDO mailbox write. Read-only policy is enforced on the host."""

        index_int, subindex_int, index_hex, subindex_hex = _normalize_sdo_address(index, subindex)
        with self.runtime_lock:
            self.sdo_raw.setdefault(int(slot), {})[(index_int, subindex_int)] = value
        return {
            "ok": True,
            "status": "PASS",
            "slot": int(slot),
            "index": index_hex,
            "subindex": subindex_hex,
            "value": value,
            "value_type": value_type,
        }

    def create_subscription(self, payload: dict[str, Any]) -> dict[str, Any]:
        with self.runtime_lock:
            subscription = Subscription.from_payload(payload, set(self.runtime.parameters))
            self.subscriptions[subscription.id] = subscription
            return {
                "ok": True,
                "status": "PASS",
                "subscription": self._subscription_dict(subscription),
            }

    def list_subscriptions(self) -> dict[str, Any]:
        with self.runtime_lock:
            return {
                "ok": True,
                "status": "PASS",
                "subscriptions": [self._subscription_dict(item) for item in self.subscriptions.values()],
            }

    def cancel_subscription(self, subscription_id: str) -> dict[str, Any]:
        with self.runtime_lock:
            removed = self.subscriptions.pop(subscription_id, None)
            return {
                "ok": removed is not None,
                "status": "PASS" if removed is not None else "WARN",
                "message": "Subscription cancelled." if removed is not None else "Subscription was not active.",
                "subscription_id": subscription_id,
            }

    def events_for_subscription(self, subscription_id: str | None = None, since: int | None = None) -> dict[str, Any]:
        with self.runtime_lock:
            events = list(self.events)
            if subscription_id:
                if subscription_id not in self.subscriptions:
                    raise ValueError(f"Unknown subscription {subscription_id!r}.")
                events = [event for event in events if event.get("subscription_id") == subscription_id]
            if since is not None:
                events = [event for event in events if int(event.get("sequence", 0)) > since]
            return {"ok": True, "status": "PASS", "events": events, "event_count": len(events)}

    def start(self, interface: str | None = None) -> dict[str, Any]:
        selected = self._resolve_interface(interface)

        # Preferred path: the real cyclic process-data master with per-path I/O.
        if self.pdo.available():
            with self.state.lock:
                if self.pdo.is_running():
                    return {"status": "PASS", "message": "Process-data master already running.", "backend": "soem_pdo_server", **self.state.status()}
            result = self.pdo.start(selected)
            with self.state.lock:
                if result.get("ok"):
                    # Point state at the helper process so status() reports RUNNING.
                    # No log-collector thread is started: the helper's stdout is the
                    # command/response channel, owned by ProcessDataServer.
                    self.state.process = self.pdo.process
                    self.state.interface = selected
                    self.state.started_at = time.time()
                    self.state.stopped_at = None
                    self.state.last_returncode = None
                    self.state.last_error = None
                    self.state.log.clear()
                    self.state.append_log(json.dumps(result))
                else:
                    self.state.last_error = str(result.get("message") or result.get("error") or "bring-up failed")
            return {
                "status": "PASS" if result.get("ok") else "FAIL",
                "message": str(result.get("message") or "Process-data master start."),
                "backend": "soem_pdo_server",
                "command": result.get("command"),
                **{k: result[k] for k in ("slaves", "obytes", "ibytes", "expected_wkc", "bringup") if k in result},
                **self.state.status(),
            }

        # Legacy/demo path: simple_ng (prints iterations, no per-path I/O).
        with self.state.lock:
            if self.state.process is not None and self.state.process.poll() is None:
                return {
                    "status": "PASS",
                    "message": "SOEM master is already running.",
                    **self.state.status(),
                }

            command = [str(self.config.simple_ng), selected]
            if self.config.start_with_sudo:
                command = ["sudo", *command]

            try:
                process = subprocess.Popen(
                    command,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.STDOUT,
                    text=True,
                    bufsize=1,
                )
            except OSError as exc:
                self.state.last_error = str(exc)
                return {"status": "FAIL", "message": str(exc), "command": command}

            self.state.process = process
            self.state.interface = selected
            self.state.started_at = time.time()
            self.state.stopped_at = None
            self.state.last_returncode = None
            self.state.last_error = None
            self.state.log.clear()
            threading.Thread(target=self._collect_output, args=(process,), daemon=True).start()

        time.sleep(0.2)
        current_status = self.state.status()
        if not current_status["running"] and current_status["master_status"] == "FAILED":
            return {
                "status": "FAIL",
                "message": "SOEM master process exited during startup.",
                "command": command,
                **current_status,
            }

        return {
            "status": "PASS",
            "message": "SOEM master process started.",
            "command": command,
            **current_status,
        }

    def stop(self, timeout_s: float = 3.0) -> dict[str, Any]:
        # Preferred path: ask the process-data master to safe-off and stop cleanly.
        if self.pdo.is_running():
            result = self.pdo.stop(timeout_s=timeout_s)
            with self.state.lock:
                if self.state.process is not None:
                    self.state.last_returncode = self.state.process.poll()
                self.state.process = None
                self.state.stopped_at = time.time()
            return {"status": "PASS", "ok": True, "message": "Process-data master stopped.", "backend": "soem_pdo_server", **result, **self.state.status()}

        with self.state.lock:
            process = self.state.process
            if process is None or process.poll() is not None:
                self.state.process = None
                self.state.stopped_at = time.time()
                return {
                    "status": "PASS",
                    "message": "SOEM master is not running.",
                    **self.state.status(),
                }

            process.send_signal(signal.SIGTERM)

        try:
            process.wait(timeout=timeout_s)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait(timeout=timeout_s)

        with self.state.lock:
            self.state.last_returncode = process.returncode
            self.state.process = None
            self.state.stopped_at = time.time()

        return {
            "status": "PASS",
            "ok": True,
            "message": "SOEM master process stopped.",
            **self.state.status(),
        }

    def pause(self) -> dict[str, Any]:
        # The CLI-backed prototype has no pause primitive yet. Returning a
        # visible WARN keeps the API shape stable without pretending to affect
        # the external master cycle.
        return {
            "ok": True,
            "status": "WARN",
            "message": "Pause is accepted by the gateway API but not implemented by the CLI backend.",
            **self.state.status(),
        }

    def _collect_output(self, process: subprocess.Popen[str]) -> None:
        assert process.stdout is not None
        for line in process.stdout:
            self.state.append_log(line)

        returncode = process.wait()
        with self.state.lock:
            self.state.last_returncode = returncode
            if self.state.process is process:
                self.state.process = None
                self.state.stopped_at = time.time()

    def _run_command(self, command: list[str], sudo: bool) -> dict[str, Any]:
        full_command = ["sudo", *command] if sudo else command
        try:
            completed = subprocess.run(full_command, capture_output=True, text=True, timeout=30)
        except (OSError, subprocess.TimeoutExpired) as exc:
            return {
                "command": full_command,
                "returncode": None,
                "stdout": "",
                "stderr": str(exc),
            }
        return {
            "command": full_command,
            "returncode": completed.returncode,
            "stdout": completed.stdout,
            "stderr": completed.stderr,
        }

    def _resolve_interface(self, interface: str | None) -> str:
        runtime_master = self.runtime.raw.get("master") if isinstance(self.runtime.raw.get("master"), dict) else {}
        selected = interface or self.runtime.raw.get("interface") or runtime_master.get("interface") or self.config.interface
        if not selected:
            raise ValueError("No EtherCAT interface configured. Pass ?interface=<ifname> or --interface.")
        return str(selected)

    def _require_parameter(self, path: str) -> RuntimeParameter:
        if not self.runtime.parameters:
            raise ValueError("No runtime EtherCAT configuration loaded. Call /ethercat/request-config first.")
        parameter = self.runtime.parameters.get(path)
        if parameter is None:
            raise ValueError(f"Unknown EtherCAT path {path!r}.")
        return parameter

    def _emit_value_change_locked(self, path: str, old_value: Any, new_value: Any, reason: str) -> int:
        emitted = 0
        for subscription in self.subscriptions.values():
            if not subscription.should_emit(path, old_value, new_value):
                continue
            self._append_event_locked(
                path,
                old_value,
                new_value,
                quality="cached_process_image",
                reason=reason,
                subscription_id=subscription.id,
            )
            emitted += 1
        return emitted

    def _append_event_locked(
        self,
        path: str,
        old_value: Any,
        new_value: Any,
        *,
        quality: str,
        reason: str,
        subscription_id: str | None = None,
    ) -> None:
        self.events.append(
            {
                "sequence": len(self.events) + 1,
                "timestamp": time.time(),
                "path": path,
                "old_value": old_value,
                "value": new_value,
                "quality": quality,
                "reason": reason,
                "subscription_id": subscription_id,
                "master_status": self.state.status()["master_status"],
            }
        )

    @staticmethod
    def _subscription_dict(subscription: Subscription) -> dict[str, Any]:
        return {
            "id": subscription.id,
            "paths": sorted(subscription.paths),
            "mode": subscription.mode,
            "deadband": subscription.deadband,
            "min_interval_s": subscription.min_interval_s,
            "created_at": subscription.created_at,
        }


class GatewayHandler(BaseHTTPRequestHandler):
    gateway: SoemGateway

    def do_GET(self) -> None:  # noqa: N802 - http.server API name
        parsed = urlparse(self.path)
        query = parse_qs(parsed.query)
        try:
            if parsed.path in {"/health", "/ethercat/health"}:
                self._json(self.gateway.health())
            elif parsed.path == "/identity":
                self._json(self.gateway.identity())
            elif parsed.path in {"/status", "/ethercat/master/status", "/ethercat/status"}:
                self._json({"ok": True, "status": "PASS", **self.gateway.state.status()})
            elif parsed.path in {"/adapters", "/ethercat/adapters"}:
                self._json(self.gateway.adapters())
            elif parsed.path in {"/inventory", "/ethercat/inventory"}:
                self._json(self.gateway.inventory(_first(query, "interface")))
            elif parsed.path in {"/logs", "/ethercat/master/log", "/ethercat/logs"}:
                log_tail = self.gateway.state.status()["log_tail"]
                tail = _first(query, "tail")
                if tail and tail.isdigit():
                    log_tail = log_tail[-int(tail) :]
                self._json({"ok": True, "status": "PASS", "log_tail": log_tail})
            elif parsed.path == "/ethercat/catalog":
                self._json(self.gateway.catalog())
            elif parsed.path == "/ethercat/snapshot":
                self._json(self.gateway.snapshot())
            elif parsed.path == "/ethercat/read":
                path = _first(query, "path")
                if not path:
                    raise ValueError("/ethercat/read requires ?path=<normalized-path>.")
                self._json(self.gateway.read(path))
            elif parsed.path.startswith("/ethercat/slave/") and parsed.path.endswith("/sdo"):
                slot = _sdo_slot(parsed.path)
                if slot is None:
                    raise ValueError(f"SDO path {parsed.path!r} must be /ethercat/slave/<slot>/sdo.")
                index = _first(query, "index")
                if not index:
                    raise ValueError("/ethercat/slave/<slot>/sdo requires ?index=<hex>.")
                self._json(self.gateway.sdo_read(slot, index, _first(query, "subindex") or "0", _first(query, "value_type")))
            elif parsed.path == "/ethercat/subscriptions":
                self._json(self.gateway.list_subscriptions())
            elif parsed.path == "/ethercat/events":
                since_raw = _first(query, "since")
                since = int(since_raw) if since_raw and since_raw.isdigit() else None
                self._json(self.gateway.events_for_subscription(_first(query, "subscription"), since=since))
            elif parsed.path == "/ethercat/events/stream":
                self._event_stream(_first(query, "subscription"))
            else:
                self._json({"status": "FAIL", "message": f"Unknown endpoint: {parsed.path}"}, HTTPStatus.NOT_FOUND)
        except ValueError as exc:
            self._json({"status": "FAIL", "message": str(exc)}, HTTPStatus.BAD_REQUEST)

    def do_POST(self) -> None:  # noqa: N802 - http.server API name
        parsed = urlparse(self.path)
        query = parse_qs(parsed.query)
        try:
            payload = self._read_json_body()
            if parsed.path in {"/start", "/ethercat/master/start", "/ethercat/processdata/start"}:
                self._json(self.gateway.start(_first(query, "interface")))
            elif parsed.path in {"/stop", "/ethercat/master/stop", "/ethercat/processdata/stop"}:
                self._json(self.gateway.stop())
            elif parsed.path == "/ethercat/master/pause":
                self._json(self.gateway.pause())
            elif parsed.path in {"/ethercat/request-config", "/ethercat/master/config-map"}:
                self._json(self.gateway.request_config(payload))
            elif parsed.path == "/ethercat/master/open":
                self._json({"ok": True, "status": "PASS", "message": "Interface accepted.", "interface": self.gateway._resolve_interface(_first(query, "interface") or payload.get("interface"))})
            elif parsed.path == "/ethercat/master/config-init":
                self._json(self.gateway.inventory(_first(query, "interface") or payload.get("interface")))
            elif parsed.path == "/ethercat/probe-inventory":
                self._json(self.gateway.inventory(str(payload.get("interface") or "") or _first(query, "interface")))
            elif parsed.path == "/ethercat/read-many":
                self._json(self.gateway.read_many(payload))
            elif parsed.path == "/ethercat/write":
                self._json(self.gateway.write(payload))
            elif parsed.path == "/ethercat/processdata/exchange":
                self._json(self.gateway.snapshot())
            elif parsed.path == "/ethercat/safe-off":
                self._json(self.gateway.safe_off())
            elif parsed.path.startswith("/ethercat/slave/") and parsed.path.endswith("/sdo"):
                slot = _sdo_slot(parsed.path)
                if slot is None:
                    raise ValueError(f"SDO path {parsed.path!r} must be /ethercat/slave/<slot>/sdo.")
                if "index" not in payload:
                    raise ValueError("SDO write payload needs index.")
                if "value" not in payload:
                    raise ValueError("SDO write payload needs value.")
                self._json(
                    self.gateway.sdo_write(
                        slot,
                        payload.get("index"),
                        payload.get("subindex", "0"),
                        payload.get("value"),
                        value_type=payload.get("value_type"),
                    )
                )
            elif parsed.path == "/ethercat/subscriptions":
                self._json(self.gateway.create_subscription(payload))
            elif parsed.path.startswith("/ethercat/subscriptions/") and parsed.path.endswith("/cancel"):
                subscription_id = parsed.path.removeprefix("/ethercat/subscriptions/").removesuffix("/cancel")
                self._json(self.gateway.cancel_subscription(subscription_id))
            else:
                self._json({"status": "FAIL", "message": f"Unknown endpoint: {parsed.path}"}, HTTPStatus.NOT_FOUND)
        except ValueError as exc:
            self._json({"status": "FAIL", "message": str(exc)}, HTTPStatus.BAD_REQUEST)

    def log_message(self, fmt: str, *args: Any) -> None:
        sys.stderr.write("[soem-gateway] " + fmt % args + "\n")

    def _json(self, payload: dict[str, Any], status: HTTPStatus = HTTPStatus.OK) -> None:
        data = json.dumps(payload, indent=2, sort_keys=True).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def _event_stream(self, subscription_id: str | None) -> None:
        payload = self.gateway.events_for_subscription(subscription_id)
        data = "".join(f"event: ethercat\ndata: {json.dumps(event, sort_keys=True)}\n\n" for event in payload["events"])
        encoded = data.encode("utf-8")
        self.send_response(HTTPStatus.OK)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Content-Length", str(len(encoded)))
        self.end_headers()
        self.wfile.write(encoded)

    def _read_json_body(self) -> dict[str, Any]:
        length = int(self.headers.get("Content-Length") or 0)
        if length <= 0:
            return {}
        raw = self.rfile.read(length).decode("utf-8")
        if not raw.strip():
            return {}
        data = json.loads(raw)
        if not isinstance(data, dict):
            raise ValueError("JSON request body must be an object.")
        return data


def _first(query: dict[str, list[str]], key: str) -> str | None:
    values = query.get(key)
    if not values:
        return None
    value = values[0].strip()
    return value or None


def _default_safe_value(payload: dict[str, Any], value_type: str) -> Any:
    if "safe_value" in payload:
        return _coerce_value(payload["safe_value"], value_type)
    if value_type == "bool":
        return False
    if value_type in {"int", "uint", "integer"}:
        return 0
    if value_type in {"float", "real"}:
        return 0.0
    return None


def _initial_value(parameter: RuntimeParameter) -> Any:
    if parameter.readable and not parameter.writable:
        return _default_safe_value(parameter.metadata, parameter.value_type)
    return parameter.safe_value


def _sdo_slot(path: str) -> int | None:
    """Return the slot from `/ethercat/slave/<slot>/sdo`, or None if malformed."""

    parts = path.strip("/").split("/")
    if len(parts) != 4 or parts[0] != "ethercat" or parts[1] != "slave" or parts[3] != "sdo":
        return None
    return int(parts[2]) if parts[2].isdigit() else None


def _normalize_sdo_address(index: Any, subindex: Any = 0) -> tuple[int, int, str, str]:
    """Normalize an SDO address to ``(index_int, subindex_int, index_hex, subindex_hex)``.

    Mirrors the framework EtherCAT gateway contract: index/subindex may be ints,
    ``0x``-prefixed strings or ESI-style ``#x`` notation; the canonical lowercase
    hex strings (``0x1018``/``0x01``) are the stable wire and report form shared
    with the Testknecht driver and the Signalzwerg gateway.
    """

    index_int = _coerce_sdo_number(index)
    subindex_int = _coerce_sdo_number(subindex)
    if not 0 <= index_int <= 0xFFFF:
        raise ValueError(f"SDO index {index!r} is outside the 16-bit range.")
    if not 0 <= subindex_int <= 0xFF:
        raise ValueError(f"SDO subindex {subindex!r} is outside the 8-bit range.")
    return index_int, subindex_int, f"0x{index_int:04x}", f"0x{subindex_int:02x}"


def _coerce_sdo_number(value: Any) -> int:
    if isinstance(value, bool):
        raise ValueError(f"SDO address {value!r} must be an integer or hex string, not a bool.")
    if isinstance(value, int):
        return value
    text = str(value).strip().lower().replace("#x", "0x")
    if not text:
        raise ValueError("SDO address must not be empty.")
    return int(text, 0)


def _coerce_value(value: Any, value_type: str) -> Any:
    normalized = value_type.lower()
    if normalized == "bool":
        if isinstance(value, str):
            return value.strip().lower() in {"1", "true", "yes", "on", "high"}
        return bool(value)
    if normalized in {"int", "uint", "integer"}:
        return int(value)
    if normalized in {"float", "real"}:
        return float(value)
    return value


def _numeric(value: Any) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def _parse_adapters(stdout: str) -> list[dict[str, str]]:
    adapters = []
    for line in stdout.splitlines():
        stripped = line.strip()
        if not stripped.startswith("- "):
            continue
        item = stripped[2:].strip()
        if "  (" in item and item.endswith(")"):
            name, desc = item[:-1].split("  (", 1)
        else:
            name, desc = item, item
        adapters.append({"name": name.strip(), "description": desc.strip()})
    return adapters


def _parse_slave_count(stdout: str) -> int | None:
    for line in stdout.splitlines():
        stripped = line.strip()
        if stripped.endswith("slaves found and configured."):
            first = stripped.split(maxsplit=1)[0]
            if first.isdigit():
                return int(first)
        if stripped == "No slaves found!":
            return 0
    return None


# Hard failures that mean the bus could not be used at all.
_HARD_ERROR_MARKERS = (
    "no socket connection",
    "excecute as root",
    "execute as root",
    "no slaves found",
    "timeout",
)
# Benign CoE SDO object-probe aborts such as
# 'Time:... SDO slave:4 index:1c13.01 error:06090011 Subindex does not exist'.
# slaveinfo emits these for objects a slave does not implement; they are
# diagnostics, not a bus/communication failure.
_SDO_PROBE_ERROR = re.compile(r"index:[0-9a-fx.]+\s+error:[0-9a-f]+", re.IGNORECASE)
_SLAVEINFO_CONFIGURED = re.compile(r"(\d+)\s+slaves found and configured", re.IGNORECASE)


def _slaveinfo_configured_ok(stdout: str) -> bool:
    """Return True when slaveinfo reports a successful enumeration (N > 0)."""

    match = _SLAVEINFO_CONFIGURED.search(stdout or "")
    return bool(match) and int(match.group(1)) > 0


def _slaveinfo_has_error(stdout: str, stderr: str) -> bool:
    combined = f"{stdout}\n{stderr}"
    # A successful enumeration is authoritative: per-object SDO probe notes do
    # not turn a found-and-configured bus into a failed inventory.
    if _slaveinfo_configured_ok(stdout):
        return _text_has_hard_error(combined)
    return _text_has_soem_error(combined)


def _text_has_hard_error(text: str) -> bool:
    lower = text.lower()
    return any(marker in lower for marker in _HARD_ERROR_MARKERS)


def _text_has_soem_error(text: str) -> bool:
    if _text_has_hard_error(text):
        return True
    # Generic 'error', but ignore benign CoE SDO object-probe aborts.
    cleaned = _SDO_PROBE_ERROR.sub("", text.lower())
    return "error" in cleaned


def _master_status(running: bool, last_error: str | None, log_tail: list[str]) -> str:
    if running:
        return "RUNNING"
    if last_error:
        return "FAILED"
    if _text_has_soem_error("\n".join(log_tail)):
        return "FAILED"
    return "STOPPED"


def _parse_slaveinfo(stdout: str) -> list[dict[str, str]]:
    slaves: list[dict[str, str]] = []
    current: dict[str, str] | None = None
    for line in stdout.splitlines():
        stripped = line.strip()
        if stripped.startswith("Slave:"):
            if current:
                slaves.append(current)
            current = {"slot": stripped.split(":", 1)[1].strip()}
        elif current and ":" in stripped:
            key, value = stripped.split(":", 1)
            normalized = key.lower().strip().replace(" ", "_").replace(".", "")
            current[normalized] = value.strip()
    if current:
        slaves.append(current)
    return slaves


def _default_binary(name: str) -> Path:
    root = Path(__file__).resolve().parents[2]
    candidates = [
        root / "build" / "darwin-arm64" / "bin" / name,
        root / "build" / "darwin-x86_64" / "bin" / name,
        root / "build" / "default" / "bin" / name,
        root / "build-darwin" / "samples" / name / name,
        root / "build-darwin-x86_64" / "samples" / name / name,
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return candidates[0]


def _parse_args(argv: list[str]) -> GatewayConfig:
    parser = argparse.ArgumentParser(description="Expose SOEM sample executables through a small HTTP gateway.")
    parser.add_argument("--interface", help="EtherCAT network interface, for example en6 or eth0.")
    parser.add_argument("--host", default="127.0.0.1", help="HTTP bind host.")
    parser.add_argument("--port", type=int, default=8765, help="HTTP bind port.")
    parser.add_argument("--simple-ng", type=Path, default=_default_binary("simple_ng"), help="Path to simple_ng executable (legacy demo master).")
    parser.add_argument("--slaveinfo", type=Path, default=_default_binary("slaveinfo"), help="Path to slaveinfo executable.")
    parser.add_argument("--pdo-server", type=Path, default=_default_binary("soem_pdo_server"), help="Path to soem_pdo_server (real cyclic process-data master). Preferred over simple_ng when present.")
    parser.add_argument("--log-lines", type=int, default=DEFAULT_LOG_LINES, help="Number of master log lines to keep.")
    parser.add_argument("--start-with-sudo", action="store_true", help="Start simple_ng through sudo.")
    parser.add_argument("--inventory-with-sudo", action="store_true", help="Run slaveinfo inventory through sudo.")
    args = parser.parse_args(argv)
    return GatewayConfig(
        interface=args.interface,
        host=args.host,
        port=args.port,
        simple_ng=args.simple_ng,
        slaveinfo=args.slaveinfo,
        pdo_server=args.pdo_server,
        log_lines=args.log_lines,
        start_with_sudo=args.start_with_sudo,
        inventory_with_sudo=args.inventory_with_sudo,
    )


def main(argv: list[str] | None = None) -> int:
    config = _parse_args(sys.argv[1:] if argv is None else argv)
    gateway = SoemGateway(config)
    gateway.state.log = deque(maxlen=config.log_lines)

    handler = type("ConfiguredGatewayHandler", (GatewayHandler,), {"gateway": gateway})
    server = ThreadingHTTPServer((config.host, config.port), handler)
    print(f"SOEM gateway listening on http://{config.host}:{config.port}")
    print(f"slaveinfo={config.slaveinfo}")
    print(f"simple_ng={config.simple_ng}")
    print(f"pdo_server={config.pdo_server} (process_data={'soem_pdo_server' if gateway.pdo.available() else 'cached_image'})")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        gateway.stop()
        server.server_close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
